# Generated by Django 6.0.3 on 2026-03-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Speech', max_length=200)),
                ('audio_file', models.FileField(upload_to='speeches/')),
                ('speech_speed_wpm', models.FloatField(blank=True, null=True)),
                ('filler_words_count', models.IntegerField(blank=True, null=True)),
                ('pause_count', models.IntegerField(blank=True, null=True)),
                ('voice_volume_stability', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('speed_score', models.FloatField(blank=True, null=True)),
                ('filler_score', models.FloatField(blank=True, null=True)),
                ('pause_score', models.FloatField(blank=True, null=True)),
                ('stability_score', models.FloatField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
